project:
  type: website

website:
  title: "Charles Lehnen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: photos.qmd
        text: Photo Gallery
      - href: documents/Charles Lehnen_CV_2025.pdf
        text: CV
  favicon: "images/favicon-32x32.png"
  page-footer:
    right: "*[This website](https://github.com/CharlesLehnen/portfolio) is built with Quarto and hosted on Github Pages. Website design adapted from [Albury Catalina](https://github.com/alburycatalina/alburycatalina.github.io).*"
  google-analytics: "G-TKLYP8KJK7"
    

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

