```{r setup, include=FALSE}

library(shiny)
library(leaflet)

# If running on a new device, get the secret code from https://www.shinyapps.io/admin/#/dashboard
# rsconnect::setAccountInfo(name='gdwsd5-charles-lehnen',
# 			  token='7BDB39CD576D8EBCCF4B5406492A3B3F',
# 			  secret='SECRET')

```

```{r, echo = FALSE}

ui <- fluidPage(
  leafletOutput("map")
)

```

```{r, echo = FALSE}

server <- function(input, output, session) {

COTOIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/COTO.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

blandingsIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/blandings.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

GalapTortIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/GalapTort.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

flyIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/fly.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

arthropodsIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/arthropods.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

elmIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/elm.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

JEPIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/JEP.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)

mojaveIcon <- makeIcon(
  iconUrl = "https://raw.githubusercontent.com/CharlesLehnen/portfolio/main/images/icons/mojave.png",
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 50
)
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("Esri.NatGeoWorldMap") %>%
      addMarkers(
        lng = -107.303802, 
        lat = 33.12007, 
        popup = "We evaluated the ecological significance of abandoned mines in New Mexico as habitats for bats to recommend them for closure or federal protection. This included the collection of habitat, LiDAR imagery, and disease metrics. Field techniques involved off-roading, hiking, and ropework, with additional avian surveys at mine closures.", 
        icon = COTOIcon
      ) %>%

      addMarkers(
        lng = -94.685898, 
        lat = 46.729553, 
        popup = "I independently monitored nesting sites of the endangered Blanding's Turtles at Murphy-Hanrehan Park, assisting with road crossings, health observations, photographic documentation, and egg translocation relocation since Blanding's exhibit natal homing", 
        icon = blandingsIcon
      ) %>%

      addMarkers(
        lng = -90.061142, 
        lat = -0.809116, 
        popup = "My doctoral research, in collaboration with the Galapagos Conservancy and Iniciativa Galápagos, explores the impact of introducing Española Giant Tortoises to Santa Fe Island to restore its ecosystem. Using drone imagery, isotope analysis, and camera traps, this project aims to take a mult-faceted approach to quantify the cascading ecological effects on this introduction.", 
        icon = GalapTortIcon
      ) %>%

      addMarkers(
        lng = -90.353943, 
        lat = -0.625109, 
        popup = "I spearheaded a 4-year comprehensive study on the natural history across five Galapagos islands, significantly contributing to the Philornis Working Group's efforts against the invasive Philornis downsi fly. This work, pivotal for understanding the ecology of Galapagos Diptera, informed P. downsi control strategies and non-target biocontrol testing. Previously, the reproductive ecology of Galapagos Diptera were largely unknown.", 
        icon = flyIcon
      ) %>%

      addMarkers(
        lng = -118.242893, 
        lat = 33.977045, 
        popup = "In collaboration with the  Los Angeles Natural History Museum (NHM) and Cal State, we examined the impact of various factors on arthropod diversity across Los Angeles, analyzing topographical, abiotic, and anthropogenic drivers. We explored the complex responses within and between six arthropod groups, revealing high regional diversity and variable spatial composition. This research underscores the nuanced relationship between urban development and biodiversity, contributing valuable insights for urban ecology and land management practices.", 
        icon = arthropodsIcon
      ) %>%

      addMarkers(
        lng = -93.08709045, 
        lat = 44.95128275, 
        popup = "I assisted in research on Dutch elm disease, nursery techniques, and urban forestry, gaining expertise in plant propagation and tree care, from seed to adult tree. Collaborating closely with Saint Paul Parks and Recreation foresters, I collected seeds and collected data across study sites. I managed 8 acres of nursery and experimental plots.", 
        icon = elmIcon
      ) %>%

      addMarkers(
        lng = -117.8986356, 
        lat = 34.12334545, 
        popup = "I led the WonderKids virtual afterschool program, creating and implementing a semester long STEM curriculum for K-5 students that highlights diversity in science with guest speakers and virtual lab tours. This approach aimed to inspire students through hands-on experiments and exposure to a variety of specific scientific careers, emphasizing inclusivity in science education.", 
        icon = JEPIcon
      ) %>%

      addMarkers(
        lng = -116.8253188, 
        lat = 39.90847444, 
        popup = "For USFWS, I collected georeferenced biometric data on vulnerable Mojave desert tortoise populations across Nevada using line-distance sampling, adhering to sterile techniques. This included assessing body condition scores, checking for Mycoplasma infection, and taking morphological measurements, with strict protocols to prevent hypothermia, dehydration, and disease spread among tortoises.", 
        icon = mojaveIcon
      ) 
   })     
}



```

```{r, echo = FALSE}

shinyApp(ui, server)

# To deploy, run this in the R console
# rsconnect::deployApp('code/shiny_map.Rmd')

```
